会員登録処理進行中
changhun2/Rails_TEST pull request #1
Opened 2017-02-24 11:21 UTC by changhun2

新しいJOINSのテーブルを追加

2017-02-27 00:28 UTC, goshanTVI commented on db/migrate/20170224055321_create_joins.rb
> +    create_table :joins do |t|
ネーミングの直しを忘れないでね。

2017-02-27 00:29 UTC, goshanTVI commented on app/controllers/user_controller.rb
> +  def index
user_controllerとjoin_controller のネーミングも

2017-02-27 00:32 UTC, goshanTVI commented
PullRequestのタイトルについて、[WIP], [WFR]みたいprefixを入れたほうがいいよ
WIP --> Work in Progress
WFR --> Wait for Review
現状は「[WIP]会員登録処理にしたほうがよい」

2017-02-28 03:03 UTC, ghost requested changes

2017-02-28 03:03 UTC, goshanTVI commented on app/controllers/join_controller.rb
> +  def index
不要コードを削除

2017-02-28 03:03 UTC, goshanTVI commented on app/controllers/join_controller.rb
> +      redirect_to user_index_path
統一するために、URLは全部 rake routesの結果で実装してください。こちらの場合は `users_path` ですね。

2017-02-28 03:03 UTC, goshanTVI commented on app/controllers/user_controller.rb
> +      puts(session[:current_user_id])
開発終わった後、debug用なprintを削除してください。
（batchとかの中に、結果を監視するための意図的なprintは別によいですが。。。）

2017-02-28 03:03 UTC, goshanTVI commented on app/controllers/user_controller.rb
> +    @Join = Join.find_by_ids_and_pwd(params[:ids],params[:pwd])
@joinか@Joinか統一してください。

2017-02-28 03:03 UTC, goshanTVI commented on app/views/join/index.html.erb
> +<%= link_to 'Login', user_index_path %>
LoginのURLはuser_index_pathにして問題ないですか？

2017-02-28 03:03 UTC, goshanTVI commented on app/views/user/index.html.erb
> +<%= link_to 'Join', join_index_path %>
こちらのURLも確認お願いします

2017-02-28 03:03 UTC, goshanTVI commented on app/views/user/index.html.erb
> +<%= form_tag('/user/:user_id/login') do %>
URLは正しいですか？:user_idはなんですか

2017-02-28 03:03 UTC, goshanTVI commented on test/controllers/join_controller_test.rb
> +  test "should get index" do
unit testsをやってもらってすばらしいです。どんどんもっと全面的なテストを書きましょう

2017-02-28 06:18 UTC, goshanTVI commented on app/models/join.rb
> +  has_many :article
has_manyというのは複数のオブジェクトを持ってるという意味ですね。だから、 `articles` のほうがわかりやすくない？

2017-02-28 11:03 UTC, changhun2 commented on app/controllers/join_controller.rb
> +  def index
ログイン画面を表示するために必要です。

2017-02-28 11:06 UTC, changhun2 commented on app/controllers/join_controller.rb
> +      redirect_to user_index_path
rake routes結果でuser_index_pathを指定しました。

2017-02-28 11:12 UTC, changhun2 commented on test/controllers/join_controller_test.rb
> +  test "should get index" do
これはgenerateコマンドを使ったら自動的に作られました。

2017-02-28 11:17 UTC, changhun2 commented on app/views/user/index.html.erb
> +<%= form_tag('/user/:user_id/login') do %>
rake routesで出たURI Patternを入れました。

2017-02-28 11:22 UTC, changhun2 commented on app/views/join/index.html.erb
> +<%= link_to 'Login', user_index_path %>
問題はないかと思いますが、もしありましたら教えていただけますか？

2017-02-28 11:22 UTC, changhun2 commented on app/views/user/index.html.erb
> +<%= link_to 'Join', join_index_path %>
問題はないかと思いますが、もしありましたら教えていただけますか？

2017-02-28 15:16 UTC, goshanTVI commented
WIP, WFRを入れようという話なんですが、commitのタイトルではなく、このPull Requestのタイトルです。変更お願いします

2017-02-28 15:17 UTC, goshanTVI commented on app/controllers/join_controller.rb
> +  def index
なるほど、失礼しました。

2017-02-28 15:32 UTC, goshanTVI commented on app/controllers/join_controller.rb
> +      redirect_to user_index_path
これは問題です。Modelの定義は普段単数の形(sはいらない)で定義して、Controllerの場合は必ず複数で定義してください(例えばUserControllerではなく、UsersControllerです)。単数の場合は前言った通り、 routes.rbの中の定義はresourcesではなく、resourceになりますよ。
Railsのほうは、単数か複数か、色んなルールがありますので、ちゃんと守ってください。Railsのガイドブックで記載されてるはずですが。。。

2017-02-28 15:35 UTC, goshanTVI commented on app/views/join/index.html.erb
> +<%= link_to 'Login', user_index_path %>
上記のネーミングのルールを守って調整してください

2017-02-28 15:36 UTC, goshanTVI commented on app/views/user/index.html.erb
> +<%= form_tag('/user/:user_id/login') do %>
こちらも、いろいろ混乱になってますね

2017-02-28 15:38 UTC, goshanTVI commented on app/views/user/index.html.erb
> +<%= link_to 'Join', join_index_path %>
こちらも、`resources :join` の場合は `JoinsController` にしてください

2017-02-28 15:39 UTC, goshanTVI commented on test/controllers/join_controller_test.rb
> +  test "should get index" do
なるほど、Rails5から自動作成されたのですね。

2017-02-28 15:48 UTC, ghost requested changes

2017-02-28 15:48 UTC, goshanTVI commented on app/controllers/articles_controller.rb
> +   puts(@user.id)
ログ確認のコードはpushする前に削除するか確認お願いします

2017-02-28 15:48 UTC, goshanTVI commented on app/controllers/login_controller.rb
> +class LoginController < ApplicationController
`LoginsController` にしたほうが正しい(routesの中で、`resources :login` を使われてますから)。具体的には、routesについてのガイドブックを参考してください

2017-02-28 15:48 UTC, goshanTVI commented on app/views/login/index.html.erb
> +<%= form_tag('/login/:login_id/login') do %>
こちらの問題もroutesの定義とControllerのネームがずれる問題だと思います。基本的には自動的にこんな感じなURLがない気がします。:login_idという意味はURLの中にlogin_idというパラメータは必要なので、ただ、今LoginsControllerがこういうパラメータを使ってないですよね。

2017-03-01 02:22 UTC, goshanTVI commented
LGTM

2017-03-01 02:23 UTC, merged